---
- name: domain user create
  hosts: "{{ win }}"
  #connection: local
  gather_facts: false
  collections:
    - windows
  tasks:
    - name: Ensure user is created and use custom credentials to create the user
      win_domain_user:
        name: area51coders
        firstname: ravi
        surname: yadav
        password: B@ond007
        state: present
        domain_username: AREA51.COM\Administrator
        domain_password: B@ond222B@ond000
        domain_server:  AREA51.COM
     # delegate_to: localhost
